### ISSUE TITLE
NullPointerException during conversion of Objects including byte[]

### ISSUE THREAD

**Issue by olley** [integrity-tf/integrity#100]
If an object containing a byte[] field is converted, a NPE occurs in *AbstractModularValueConverter.convertPlainValueToTargetType()* because no Conversion class is found.

This problem e.g. occurrs when using forks during the update of variable values.
Example steps to reproduce:
- run stuff on a fork
- store an object with a non-null byte[] field into a variable
- run stuff on a fork

**Comment by S1artie** [comment]
This issue is indeed a bug. Actually it is far more crititcal than simply creating problems when byte arrays are put into variables while forks are running - it prevents instances of arbitrary class hierarchies from being synced to forks, which should actually be possible (as long as the hierarchy is fully serializable, of course).
I've fixed it now and will push out an official bugfix release later this day.

**Comment by S1artie** [comment]
Follow-up issue #101 created which came up while fixing this one.
