### ISSUE TITLE
Synchronization of suite parameters overrides empty values on forks

### ISSUE THREAD

**Issue by olley** [integrity-tf/integrity#167]
Consider the following test suite:

```
forkdef myFork
suitedef forkTest with
	suite otherSuite on myFork
	suite otherSuite aParam: "test"
	suite otherSuite on myFork // aParameter is still "test"
suiteend
suitedef otherSuite gets aParam with
	test fixtures.returnObject object: aParam = "test"
suiteend
```

Since the third call of "otherSuite" on "myFork" includes no parameter, it should be treated as "null" (with test results expected to be "failure, success, failure"), however instead the value "test" from the previous invocation is injected.

**Comment by S1artie** [comment]
There was actually quite a bit of inconsistency in the way suite parameters were cleared after leaving the respective suites between forks and the master, which created this problem here. I have now attempted to synchronize this behavior, so forks and master should have an identical view on variable values (and suite params are just suite-scoped variables in the end).

It would come as little surprise if this would even fix this strange non-reproducable issue #150
